package com.netwatch.phone.ui;

import android.content.Context;
import android.graphics.*;
import android.view.MotionEvent;
import android.view.View;
import java.util.*;

public final class GlassPhoneView extends View {
    public interface Callback { void placeCall(String number); void openSettings(); void openContactSearch(); }
    public static final class RecentCall {
        public final String name, number, detail; public final boolean missed;
        public RecentCall(String n,String num,String d,boolean m){name=n==null?"":n;number=num==null?"":num;detail=d==null?"":d;missed=m;}
    }
    public static final class ContactItem {
        public final String name, number;
        public ContactItem(String n,String num){name=n==null?"":n;number=num==null?"":num;}
    }
    private enum Page { FAVORITES, RECENTS, CONTACTS, KEYPAD }
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG), line=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final Callback callback; private final List<RecentCall> recents=new ArrayList<>(); private final List<ContactItem> contacts=new ArrayList<>();
    private final StringBuilder digits=new StringBuilder();
    private final String[][] keys={{"1",""},{"2","ABC"},{"3","DEF"},{"4","GHI"},{"5","JKL"},{"6","MNO"},{"7","PQRS"},{"8","TUV"},{"9","WXYZ"},{"*",""},{"0","+"},{"#",""}};
    private Page page=Page.RECENTS; private float d,sd,w,h,navTop,downY; private int contactOffset,recentOffset; private Throwable drawError;

    public GlassPhoneView(Context c,Callback cb){super(c);callback=cb;d=getResources().getDisplayMetrics().density;sd=getResources().getDisplayMetrics().scaledDensity;setClickable(true);setBackgroundColor(Color.rgb(7,18,31));}
    public void setRecentCalls(List<RecentCall> x){recents.clear();if(x!=null)recents.addAll(x);recentOffset=fit(recentOffset,recents.size(),recentRows());invalidate();}
    public void setContacts(List<ContactItem> x){contacts.clear();if(x!=null)contacts.addAll(x);contactOffset=fit(contactOffset,contacts.size(),contactRows());invalidate();}
    public void showKeypad(String s){page=Page.KEYPAD;digits.setLength(0);if(s!=null)digits.append(s);invalidate();}
    @Override protected void onSizeChanged(int W,int H,int ow,int oh){w=W;h=H;navTop=Math.max(dp(480),h-dp(88));}

    @Override protected void onDraw(Canvas c){super.onDraw(c);try{drawError=null;bg(c);header(c);if(page==Page.KEYPAD)keypad(c);else if(page==Page.CONTACTS)contacts(c);else if(page==Page.FAVORITES)favorites(c);else recents(c);nav(c);}catch(Throwable e){drawError=e;c.drawColor(Color.rgb(8,20,34));txt(c,"NetWatch Phone",dp(24),dp(60),sp(28),Color.WHITE,true,Paint.Align.LEFT);txt(c,"Glass safe mode",dp(24),dp(94),sp(15),0xFF9ED4FF,true,Paint.Align.LEFT);}}

    private void bg(Canvas c){p.setShader(new LinearGradient(0,0,Math.max(1,w),Math.max(1,h),new int[]{0xFF274F74,0xFF102B47,0xFF06111F},new float[]{0,.48f,1},Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(0x18FFFFFF);c.drawCircle(w*.16f,h*.17f,dp(110),p);p.setColor(0x166CC7FF);c.drawCircle(w*.82f,h*.30f,dp(150),p);p.setColor(0x125FE6C4);c.drawCircle(w*.54f,h*.60f,dp(180),p);}
    private void header(Canvas c){float y=dp(30);shield(c,dp(31),y+dp(21),dp(18));txt(c,"NetWatch Phone",dp(60),y+dp(22),sp(26),Color.WHITE,true,Paint.Align.LEFT);txt(c,page==Page.KEYPAD?"Private. Protected. In your control.":"Private calls for a safer, quieter you.",dp(60),y+dp(43),sp(12),0xFFBED4E9,false,Paint.Align.LEFT);RectF r=new RectF(w-dp(57),y,w-dp(17),y+dp(40));glass(c,r,dp(20),0x2DFFFFFF,0x70FFFFFF);p.setColor(Color.WHITE);c.drawCircle(r.centerX()-dp(7),r.centerY(),dp(1.5f),p);c.drawCircle(r.centerX(),r.centerY(),dp(1.5f),p);c.drawCircle(r.centerX()+dp(7),r.centerY(),dp(1.5f),p);}

    private void recents(Canvas c){float y=dp(95);search(c,y,"Search contacts or numbers");y+=dp(60);float g=dp(7),cw=(w-dp(36)-g*2)/3;chip(c,"All",dp(18),y,cw,true);chip(c,"Missed",dp(18)+cw+g,y,cw,false);chip(c,"Voicemail",dp(18)+(cw+g)*2,y,cw,false);y+=dp(55);txt(c,"Recent calls",dp(20),y,sp(15),Color.WHITE,true,Paint.Align.LEFT);int rows=recentRows(),end=Math.min(recents.size(),recentOffset+rows);if(!recents.isEmpty())txt(c,(recentOffset+1)+"–"+end+" of "+recents.size(),w-dp(20),y,sp(10.5f),0xFFAFC5D9,false,Paint.Align.RIGHT);y+=dp(13);if(recents.isEmpty()){empty(c,"Your recent calls","Make NetWatch your default phone app to show call history.",y+dp(80));return;}for(int i=recentOffset;i<end&&y+dp(68)<navTop;i++){RecentCall r=recents.get(i);RectF box=new RectF(dp(15),y,w-dp(15),y+dp(63));glass(c,box,dp(21),0x19FFFFFF,0x37FFFFFF);float cy=box.centerY();avatar(c,dp(47),cy,dp(21),display(r),r.missed);txt(c,display(r),dp(79),cy-dp(3),sp(14.5f),Color.WHITE,false,Paint.Align.LEFT);txt(c,r.detail,dp(79),cy+dp(18),sp(11),r.missed?0xFFFF7786:0xFFC8D7E6,false,Paint.Align.LEFT);phone(c,w-dp(43),cy,dp(18),0x25FFFFFF);y+=dp(68);}hint(c,recentOffset,recents.size(),rows);}

    private void contacts(Canvas c){float y=dp(100);search(c,y,"Search all contacts");y+=dp(72);txt(c,"Contacts",dp(20),y,sp(25),Color.WHITE,true,Paint.Align.LEFT);int rows=contactRows(),end=Math.min(contacts.size(),contactOffset+rows);if(!contacts.isEmpty())txt(c,(contactOffset+1)+"–"+end+" of "+contacts.size(),w-dp(20),y,sp(10.5f),0xFFAFC5D9,false,Paint.Align.RIGHT);y+=dp(18);if(contacts.isEmpty()){empty(c,"No contacts yet","Allow Contacts permission from the menu.",y+dp(80));return;}for(int i=contactOffset;i<end&&y+dp(64)<navTop;i++){ContactItem it=contacts.get(i);float cy=y+dp(30);avatar(c,dp(47),cy,dp(21),it.name,false);txt(c,it.name,dp(79),cy-dp(3),sp(14.5f),Color.WHITE,false,Paint.Align.LEFT);txt(c,it.number,dp(79),cy+dp(17),sp(11),0xFFC8D7E6,false,Paint.Align.LEFT);phone(c,w-dp(43),cy,dp(18),0x20FFFFFF);line.setColor(0x25FFFFFF);line.setStrokeWidth(dp(1));c.drawLine(dp(79),y+dp(61),w-dp(18),y+dp(61),line);y+=dp(66);}hint(c,contactOffset,contacts.size(),rows);}

    private void favorites(Canvas c){float y=dp(111);txt(c,"Favorites",dp(20),y,sp(27),Color.WHITE,true,Paint.Align.LEFT);txt(c,"People you call most",dp(20),y+dp(24),sp(12),0xFFBED4E9,false,Paint.Align.LEFT);y+=dp(50);if(contacts.isEmpty()){empty(c,"No favorites yet","Your contacts will appear here.",y+dp(75));return;}for(int i=0;i<Math.min(6,contacts.size())&&y+dp(72)<navTop;i++){ContactItem it=contacts.get(i);RectF r=new RectF(dp(18),y,w-dp(18),y+dp(68));glass(c,r,dp(23),0x1CFFFFFF,0x3DFFFFFF);avatar(c,dp(49),r.centerY(),dp(22),it.name,false);txt(c,it.name,dp(83),r.centerY()-dp(3),sp(15),Color.WHITE,false,Paint.Align.LEFT);txt(c,it.number,dp(83),r.centerY()+dp(18),sp(11),0xFFC8D7E6,false,Paint.Align.LEFT);phone(c,w-dp(46),r.centerY(),dp(19),0x25FFFFFF);y+=dp(77);}}

    private void keypad(Canvas c){float top=dp(106);RectF display=new RectF(dp(27),top,w-dp(27),top+dp(70));glass(c,display,dp(27),0x32FFFFFF,0x80FFFFFF);String shown=digits.length()==0?"Enter a number":digits.toString();txt(c,shown,display.centerX(),display.centerY()+dp(8),digits.length()==0?sp(16):sp(26),digits.length()==0?0xFFB9CBE0:Color.WHITE,false,Paint.Align.CENTER);if(digits.length()>0){RectF b=new RectF(w-dp(70),top+dp(19),w-dp(38),top+dp(51));glass(c,b,dp(14),0x22FFFFFF,0x45FFFFFF);txt(c,"×",b.centerX(),b.centerY()+dp(7),sp(20),Color.WHITE,true,Paint.Align.CENTER);}float cx=w/2,colGap=Math.min(dp(112),w/3.25f),sx=cx-colGap,sy=top+dp(112),rg=Math.min(dp(92),(navTop-sy-dp(78))/4.1f),rad=Math.min(dp(37),colGap*.34f);for(int i=0;i<12;i++){int col=i%3,row=i/3;key(c,sx+col*colGap,sy+row*rg,rad,keys[i][0],keys[i][1]);}float cy=sy+rg*4-dp(2);p.setShader(new LinearGradient(cx-dp(35),cy-dp(35),cx+dp(35),cy+dp(35),0xFF70EA6A,0xFF12A13D,Shader.TileMode.CLAMP));c.drawCircle(cx,cy,dp(37),p);p.setShader(null);phoneGlyph(c,cx,cy,Color.WHITE,1.2f);}

    private void nav(Canvas c){RectF n=new RectF(dp(11),navTop,w-dp(11),h-dp(10));glass(c,n,dp(27),0x42101A29,0x65FFFFFF);String[] labels={"Favorites","Recents","Contacts","Keypad"};Page[] pages={Page.FAVORITES,Page.RECENTS,Page.CONTACTS,Page.KEYPAD};float slot=n.width()/4;for(int i=0;i<4;i++){float cx=n.left+slot*(i+.5f);boolean sel=page==pages[i];if(sel)glass(c,new RectF(cx-slot*.39f,n.top+dp(7),cx+slot*.39f,n.bottom-dp(7)),dp(22),0x605294EE,0xB5D7EAFF);navIcon(c,i,cx,n.top+dp(27),sel?Color.WHITE:0xFFD1DBE5);txt(c,labels[i],cx,n.top+dp(63),sp(10),sel?Color.WHITE:0xFFD1DBE5,false,Paint.Align.CENTER);}}

    private void search(Canvas c,float y,String label){RectF r=new RectF(dp(18),y,w-dp(18),y+dp(49));glass(c,r,dp(20),0x27FFFFFF,0x60FFFFFF);line.setStyle(Paint.Style.STROKE);line.setStrokeWidth(dp(2));line.setColor(0xFFE6EDF5);c.drawCircle(dp(38),y+dp(22),dp(7),line);c.drawLine(dp(43),y+dp(27),dp(49),y+dp(33),line);line.setStyle(Paint.Style.FILL);txt(c,label,dp(58),y+dp(29),sp(12.5f),0xFFE2ECF5,false,Paint.Align.LEFT);}
    private void glass(Canvas c,RectF r,float rad,int fill,int border){p.setShader(new LinearGradient(r.left,r.top,r.right,r.bottom,bright(fill,1.2f),dark(fill,.78f),Shader.TileMode.CLAMP));c.drawRoundRect(r,rad,rad,p);p.setShader(null);line.setStyle(Paint.Style.STROKE);line.setStrokeWidth(dp(1));line.setColor(border);c.drawRoundRect(r,rad,rad,line);line.setStyle(Paint.Style.FILL);}
    private void chip(Canvas c,String s,float x,float y,float cw,boolean sel){RectF r=new RectF(x,y,x+cw,y+dp(38));glass(c,r,dp(17),sel?0x70599FF2:0x1EFFFFFF,sel?0xCCDDF0FF:0x3AFFFFFF);txt(c,s,r.centerX(),r.centerY()+dp(5),sp(12),Color.WHITE,false,Paint.Align.CENTER);}
    private void key(Canvas c,float x,float y,float rad,String main,String sub){RectF r=new RectF(x-rad,y-rad,x+rad,y+rad);glass(c,r,rad,0x31FFFFFF,0x73FFFFFF);txt(c,main,x,y+(sub.isEmpty()?dp(9):dp(2)),sp(29),Color.WHITE,false,Paint.Align.CENTER);if(!sub.isEmpty())txt(c,sub,x,y+dp(22),sp(10.5f),0xFFE7EEF6,false,Paint.Align.CENTER);}
    private void avatar(Canvas c,float x,float y,float r,String label,boolean missed){int seed=label==null?0:label.hashCode();p.setColor(Color.rgb(clamp(missed?190:65+Math.abs(seed%55)),clamp(missed?70:95+Math.abs((seed/7)%65)),clamp(missed?92:130+Math.abs((seed/13)%70))));c.drawCircle(x,y,r,p);txt(c,initials(label),x,y+dp(5),sp(13),Color.WHITE,true,Paint.Align.CENTER);}
    private void phone(Canvas c,float x,float y,float r,int bg){p.setColor(bg);c.drawCircle(x,y,r,p);phoneGlyph(c,x,y,Color.WHITE,.68f);}
    private void phoneGlyph(Canvas c,float x,float y,int color,float scale){line.setStyle(Paint.Style.STROKE);line.setStrokeCap(Paint.Cap.ROUND);line.setStrokeWidth(dp(4.5f)*scale);line.setColor(color);c.drawArc(new RectF(x-dp(11)*scale,y-dp(11)*scale,x+dp(11)*scale,y+dp(11)*scale),133,93,false,line);line.setStrokeCap(Paint.Cap.BUTT);line.setStyle(Paint.Style.FILL);}
    private void shield(Canvas c,float x,float y,float r){Path s=new Path();s.moveTo(x,y-r);s.lineTo(x+r*.78f,y-r*.60f);s.lineTo(x+r*.66f,y+r*.42f);s.quadTo(x,y+r*1.10f,x-r*.66f,y+r*.42f);s.lineTo(x-r*.78f,y-r*.60f);s.close();p.setShader(new LinearGradient(x-r,y-r,x+r,y+r,0xFF83E3FF,0xFF1F78D0,Shader.TileMode.CLAMP));c.drawPath(s,p);p.setShader(null);p.setColor(Color.WHITE);c.drawCircle(x,y,dp(3),p);}
    private void navIcon(Canvas c,int i,float x,float y,int color){p.setColor(color);line.setColor(color);line.setStyle(Paint.Style.STROKE);line.setStrokeWidth(dp(2));if(i==0){Path s=new Path();for(int k=0;k<10;k++){double a=-Math.PI/2+k*Math.PI/5;float r=k%2==0?dp(10):dp(4.5f),px=x+(float)Math.cos(a)*r,py=y+(float)Math.sin(a)*r;if(k==0)s.moveTo(px,py);else s.lineTo(px,py);}s.close();c.drawPath(s,p);}else if(i==1){c.drawCircle(x,y,dp(9),line);c.drawLine(x,y,x,y-dp(5),line);c.drawLine(x,y,x+dp(4),y+dp(2),line);}else if(i==2){c.drawCircle(x,y-dp(5),dp(4.5f),p);c.drawRoundRect(new RectF(x-dp(8),y+dp(2),x+dp(8),y+dp(10)),dp(5),dp(5),p);}else{for(int rr=-1;rr<=1;rr++)for(int cc=-1;cc<=1;cc++)c.drawCircle(x+cc*dp(7),y+rr*dp(7),dp(2.8f),p);}line.setStyle(Paint.Style.FILL);}
    private void empty(Canvas c,String title,String sub,float y){RectF r=new RectF(dp(24),y-dp(50),w-dp(24),y+dp(60));glass(c,r,dp(26),0x1CFFFFFF,0x3CFFFFFF);txt(c,title,w/2,y,sp(17),Color.WHITE,true,Paint.Align.CENTER);txt(c,sub,w/2,y+dp(27),sp(11.5f),0xFFBED4E9,false,Paint.Align.CENTER);}
    private void hint(Canvas c,int off,int total,int rows){if(total<=rows)return;String s=(off>0?"↑":"")+(off>0&&off+rows<total?"  ":"")+(off+rows<total?"↓":"");txt(c,s,w-dp(24),navTop-dp(10),sp(13),0x99D7E9F8,false,Paint.Align.RIGHT);}
    private void txt(Canvas c,String s,float x,float y,float size,int color,boolean bold,Paint.Align align){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(color);p.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));p.setTextSize(size);p.setTextAlign(align);c.drawText(s==null?"":s,x,y,p);}
    private String display(RecentCall r){return !r.name.trim().isEmpty()?r.name:(!r.number.trim().isEmpty()?r.number:"Unknown Caller");}
    private String initials(String s){if(s==null||s.trim().isEmpty())return "?";String[] a=s.trim().split("\\s+");String z=a[0].substring(0,1).toUpperCase();if(a.length>1)z+=a[a.length-1].substring(0,1).toUpperCase();return z;}
    private int recentRows(){return navTop<=0?6:Math.max(3,(int)((navTop-dp(223))/dp(68)));}
    private int contactRows(){return navTop<=0?7:Math.max(3,(int)((navTop-dp(190))/dp(66)));}
    private int fit(int off,int total,int rows){return Math.max(0,Math.min(Math.max(0,total-rows),off));}
    private static int clamp(int n){return Math.max(0,Math.min(255,n));}
    private static int bright(int c,float f){return Color.argb(Math.min(255,(int)(Color.alpha(c)*f)),Color.red(c),Color.green(c),Color.blue(c));}
    private static int dark(int c,float f){return Color.argb(Math.max(0,(int)(Color.alpha(c)*f)),Color.red(c),Color.green(c),Color.blue(c));}

    @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();if(e.getAction()==MotionEvent.ACTION_DOWN){downY=y;return true;}if(e.getAction()!=MotionEvent.ACTION_UP)return true;if(drawError!=null){callback.openSettings();return true;}float dy=y-downY;if(Math.abs(dy)>dp(35)){if(page==Page.CONTACTS){int rows=contactRows();contactOffset=fit(contactOffset+(dy<0?rows:-rows),contacts.size(),rows);invalidate();return true;}if(page==Page.RECENTS){int rows=recentRows();recentOffset=fit(recentOffset+(dy<0?rows:-rows),recents.size(),rows);invalidate();return true;}}if(y>=navTop){float slot=(w-dp(22))/4;int i=(int)((x-dp(11))/slot);if(i>=0&&i<4){page=Page.values()[i];invalidate();}return true;}if(x>w-dp(75)&&y<dp(90)){callback.openSettings();return true;}if(page==Page.RECENTS&&y>=dp(95)&&y<=dp(147)){callback.openContactSearch();return true;}if(page==Page.CONTACTS&&y>=dp(100)&&y<=dp(152)){callback.openContactSearch();return true;}if(page==Page.KEYPAD)return keypadTouch(x,y);if(page==Page.RECENTS)return recentTouch(x,y);if(page==Page.CONTACTS)return contactTouch(x,y,false);if(page==Page.FAVORITES)return contactTouch(x,y,true);return true;}
    private boolean keypadTouch(float x,float y){float top=dp(106);if(digits.length()>0&&x>w-dp(82)&&y>top&&y<top+dp(75)){digits.deleteCharAt(digits.length()-1);invalidate();return true;}float cx=w/2,colGap=Math.min(dp(112),w/3.25f),sx=cx-colGap,sy=top+dp(112),rg=Math.min(dp(92),(navTop-sy-dp(78))/4.1f),hit=Math.min(dp(44),colGap*.40f);for(int i=0;i<12;i++){int col=i%3,row=i/3;float kx=sx+col*colGap,ky=sy+row*rg;if(dist(x,y,kx,ky)<=hit){digits.append(keys[i][0]);invalidate();return true;}}float cy=sy+rg*4-dp(2);if(dist(x,y,cx,cy)<=dp(48)&&digits.length()>0)callback.placeCall(digits.toString());return true;}
    private boolean recentTouch(float x,float y){int local=(int)((y-dp(223))/dp(68)),i=recentOffset+local;if(local>=0&&i>=0&&i<recents.size())callback.placeCall(recents.get(i).number);return true;}
    private boolean contactTouch(float x,float y,boolean fav){float start=fav?dp(161):dp(190),row=fav?dp(77):dp(66);int local=(int)((y-start)/row),i=(fav?0:contactOffset)+local;if(local>=0&&i>=0&&i<contacts.size())callback.placeCall(contacts.get(i).number);return true;}
    private static float dist(float x1,float y1,float x2,float y2){float dx=x1-x2,dy=y1-y2;return(float)Math.sqrt(dx*dx+dy*dy);} private float dp(float v){return v*d;} private float sp(float v){return v*sd;}
}
